// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransparenciaPE.Infrastructure.Data;

#nullable disable

namespace TransparenciaPE.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401035658_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransparenciaPE.Domain.Entities.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CnpjFornecedor")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fornecedor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NumeroContrato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Objeto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OrgaoGovernoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorContrato")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CnpjFornecedor")
                        .HasDatabaseName("ix_contratos_cnpj");

                    b.HasIndex("NumeroContrato")
                        .IsUnique()
                        .HasDatabaseName("ix_contratos_numero");

                    b.HasIndex("OrgaoGovernoId");

                    b.ToTable("contratos", (string)null);
                });

            modelBuilder.Entity("TransparenciaPE.Domain.Entities.Empenho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<string>("ClassificacaoMcasp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CnpjCredor")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Credor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("DataEmpenho")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NumeroEmpenho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("OrgaoGovernoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CnpjCredor")
                        .HasDatabaseName("ix_empenhos_cnpj");

                    b.HasIndex("DataEmpenho")
                        .HasDatabaseName("ix_empenhos_data");

                    b.HasIndex("OrgaoGovernoId");

                    b.HasIndex("NumeroEmpenho", "Ano")
                        .IsUnique()
                        .HasDatabaseName("ix_empenhos_numero_ano");

                    b.ToTable("empenhos", (string)null);
                });

            modelBuilder.Entity("TransparenciaPE.Domain.Entities.Liquidacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataLiquidacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpenhoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroLiquidacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmpenhoId");

                    b.ToTable("liquidacoes", (string)null);
                });

            modelBuilder.Entity("TransparenciaPE.Domain.Entities.OrgaoGoverno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_orgaos_codigo");

                    b.HasIndex("Nome")
                        .HasDatabaseName("ix_orgaos_nome");

                    b.ToTable("orgaos_governo", (string)null);
                });

            modelBuilder.Entity("TransparenciaPE.Domain.Entities.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LiquidacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroPagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LiquidacaoId");

                    b.ToTable("pagamentos", (string)null);
                });

            modelBuilder.Entity("TransparenciaPE.Domain.Entities.Contrato", b =>
                {
                    b.HasOne("TransparenciaPE.Domain.Entities.OrgaoGoverno", "OrgaoGoverno")
                        .WithMany("Contratos")
                        .HasForeignKey("OrgaoGovernoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrgaoGoverno");
                });

            modelBuilder.Entity("TransparenciaPE.Domain.Entities.Empenho", b =>
                {
                    b.HasOne("TransparenciaPE.Domain.Entities.OrgaoGoverno", "OrgaoGoverno")
                        .WithMany("Empenhos")
                        .HasForeignKey("OrgaoGovernoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrgaoGoverno");
                });

            modelBuilder.Entity("TransparenciaPE.Domain.Entities.Liquidacao", b =>
                {
                    b.HasOne("TransparenciaPE.Domain.Entities.Empenho", "Empenho")
                        .WithMany("Liquidacoes")
                        .HasForeignKey("EmpenhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empenho");
                });

            modelBuilder.Entity("TransparenciaPE.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("TransparenciaPE.Domain.Entities.Liquidacao", "Liquidacao")
                        .WithMany("Pagamentos")
                        .HasForeignKey("LiquidacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liquidacao");
                });

            modelBuilder.Entity("TransparenciaPE.Domain.Entities.Empenho", b =>
                {
                    b.Navigation("Liquidacoes");
                });

            modelBuilder.Entity("TransparenciaPE.Domain.Entities.Liquidacao", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("TransparenciaPE.Domain.Entities.OrgaoGoverno", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Empenhos");
                });
#pragma warning restore 612, 618
        }
    }
}
